import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface Translations {
  [key: string]: {
    en: string;
    es: string;
  };
}

const translations: Translations = {
  'login.title': { en: 'Asciende Metabolic Lab', es: 'Asciende Metabolic Lab' },
  'login.subtitle': { en: 'Sign in with your HUB credentials', es: 'Inicia sesión con tus credenciales del HUB' },
  'login.email': { en: 'Email', es: 'Correo Electrónico' },
  'login.password': { en: 'Password', es: 'Contraseña' },
  'login.signin': { en: 'Sign In', es: 'Iniciar Sesión' },
  'login.signingin': { en: 'Signing in...', es: 'Iniciando sesión...' },
  'login.footer': { en: 'Uses the same credentials as Asciende HUB', es: 'Usa las mismas credenciales que Asciende HUB' },

  'setup.title': { en: 'Initial Setup', es: 'Configuración Inicial' },
  'setup.subtitle': { en: 'Create your first admin account', es: 'Crea tu primera cuenta de administrador' },
  'setup.fullname': { en: 'Full Name', es: 'Nombre Completo' },
  'setup.create': { en: 'Create Admin Account', es: 'Crear Cuenta de Administrador' },
  'setup.creating': { en: 'Creating Admin...', es: 'Creando Administrador...' },
  'setup.gotologin': { en: 'Go to Login →', es: 'Ir a Inicio de Sesión →' },

  'app.title': { en: 'Asciende Metabolic Lab', es: 'Asciende Metabolic Lab' },
  'app.subtitle': { en: 'Professional Physiological Testing System', es: 'Sistema Profesional de Pruebas Fisiológicas' },
  'app.logout': { en: 'Logout', es: 'Cerrar Sesión' },
  'app.adminpanel': { en: 'Admin Panel', es: 'Panel de Administración' },
  'app.backathletes': { en: '← Back to Athletes', es: '← Volver a Atletas' },
  'app.newtest': { en: '+ New Test', es: '+ Nueva Prueba' },
  'app.manageathletes': { en: '← Manage Athletes', es: '← Gestionar Atletas' },
  'app.backselection': { en: '← Back to Selection', es: '← Volver a Selección' },
  'app.canceltest': { en: '← Cancel Test', es: '← Cancelar Prueba' },
  'app.backtests': { en: '← Back to Tests', es: '← Volver a Pruebas' },
  'app.loading': { en: 'Loading...', es: 'Cargando...' },

  'dashboard.title': { en: 'Dashboard', es: 'Panel de Control' },
  'dashboard.totalAthletes': { en: 'Total Athletes', es: 'Total de Atletas' },
  'dashboard.totalTests': { en: 'Total Tests', es: 'Total de Pruebas' },
  'dashboard.recentActivity': { en: 'Recent Activity', es: 'Actividad Reciente' },

  'evaluations.title': { en: 'Evaluations', es: 'Evaluaciones' },
  'evaluations.loading': { en: 'Loading...', es: 'Cargando...' },
  'evaluations.noEvaluations': { en: 'No evaluations found', es: 'No se encontraron evaluaciones' },
  'evaluations.athlete': { en: 'Athlete', es: 'Atleta' },
  'evaluations.testType': { en: 'Test Type', es: 'Tipo de Prueba' },
  'evaluations.testDate': { en: 'Test Date', es: 'Fecha de Prueba' },
  'evaluations.created': { en: 'Created', es: 'Creado' },
  'evaluations.unknown': { en: 'Unknown', es: 'Desconocido' },

  'layout.logout': { en: 'Logout', es: 'Cerrar Sesión' },
  'layout.lightMode': { en: 'Light Mode', es: 'Modo Claro' },
  'layout.darkMode': { en: 'Dark Mode', es: 'Modo Oscuro' },
  'layout.light': { en: 'Light', es: 'Claro' },
  'layout.dark': { en: 'Dark', es: 'Oscuro' },
  'layout.english': { en: 'English', es: 'Inglés' },
  'layout.spanish': { en: 'Spanish', es: 'Español' },
  'layout.more': { en: 'More', es: 'Más' },

  'kerr.title': { en: 'Body Composition — Kerr Method (5 compartments)', es: 'Composición Corporal — Método Kerr (5 compartimentos)' },
  'kerr.tab.conclusions': { en: 'Conclusions', es: 'Conclusiones' },
  'kerr.tab.results': { en: 'Results', es: 'Resultados' },
  'kerr.tab.targets': { en: 'Targets', es: 'Objetivos' },
  'kerr.somatotype': { en: 'Somatotype', es: 'Somatotipo' },
  'kerr.endoMesoEcto': { en: 'Endo – Meso – Ecto', es: 'Endo – Meso – Ecto' },
  'kerr.bmi': { en: 'BMI', es: 'IMC' },
  'kerr.surfaceArea': { en: 'Body Surface Area', es: 'Superficie corporal' },
  'kerr.zScoresTitle': { en: 'Z-scores (Phantom Reference)', es: 'Z-scores (Referencia Fantasma)' },
  'kerr.allCompartments': { en: 'All Compartments', es: 'Todos los compartimentos' },
  'kerr.compartment': { en: 'Compartment', es: 'Compartimento' },
  'kerr.comp.muscle': { en: 'Muscle', es: 'Muscular' },
  'kerr.comp.adipose': { en: 'Adipose', es: 'Adiposa' },
  'kerr.comp.bone': { en: 'Bone', es: 'Ósea' },
  'kerr.comp.residual': { en: 'Residual', es: 'Residual' },
  'kerr.comp.skin': { en: 'Skin', es: 'Piel' },
  'kerr.comp.boneHead': { en: '↳ Bone (head)', es: '↳ Ósea cabeza' },
  'kerr.comp.boneBody': { en: '↳ Bone (body)', es: '↳ Ósea cuerpo' },
  'kerr.structuredWeight': { en: 'Structured Weight vs Gross Weight', es: 'Peso Estructurado vs Peso Bruto' },
  'kerr.structuredWeightLabel': { en: 'Structured weight', es: 'Peso estructurado' },
  'kerr.diffLabel': { en: 'Difference (Gross - Struct.)', es: 'Diferencia (Bruto - Estruct.)' },
  'kerr.techError': { en: 'Technical Error (%)', es: 'Error técnico (%)' },
  'kerr.sum6Skinfolds': { en: 'Sum 6 Skinfolds', es: 'Suma 6 pliegues' },
  'kerr.muscleBoneRatio': { en: 'Muscle/Bone Ratio', es: 'Ratio Músculo/Óseo' },
  'kerr.ballastIndex': { en: 'Ballast Index', es: 'Índice de Lastre' },
  'kerr.adiposeMuscleRatio': { en: 'Adipose/Muscle Ratio', es: 'Ratio Adiposo/Muscular' },
  'kerr.dashboard.title': { en: 'Kerr Body Composition Analysis Dashboard', es: 'Panel de Análisis de Composición Corporal Kerr' },
  'kerr.dashboard.avgAdipose': { en: 'Average Adipose Mass', es: 'Masa Adiposa Promedio' },
  'kerr.dashboard.avgMuscle': { en: 'Average Muscle Mass', es: 'Masa Muscular Promedio' },
  'kerr.dashboard.avgBone': { en: 'Average Bone Mass', es: 'Masa Ósea Promedio' },
  'kerr.dashboard.totalAssessments': { en: 'Total Assessments:', es: 'Total de Evaluaciones:' },
  'kerr.dashboard.noData': { en: 'No data available', es: 'Sin datos disponibles' },

  'targets.intro': { en: 'Enter the target for each compartment. The system calculates how many kg need to be gained or lost to reach it.', es: 'Ingresá el objetivo para cada compartimento. El sistema calcula cuántos kg hay que ganar o perder para alcanzarlo.' },
  'targets.adiposeMass': { en: 'Adipose Mass', es: 'Masa Adiposa' },
  'targets.muscleMass': { en: 'Muscle Mass', es: 'Masa Muscular' },
  'targets.currentZ': { en: 'Current Z:', es: 'Z actual:' },
  'targets.current': { en: 'Current:', es: 'Actual:' },
  'targets.currentSum6': { en: 'Current sum 6 skinfolds:', es: 'Suma 6 pliegues actual:' },
  'targets.currentRatio': { en: 'Current Muscle/Bone Ratio:', es: 'Ratio Músculo/Óseo actual:' },
  'targets.byZScore': { en: 'By Z-score', es: 'Por Z-score' },
  'targets.bySkinfolds': { en: 'By Sum 6 Skinfolds', es: 'Por suma 6 pliegues' },
  'targets.byRatio': { en: 'By M/B Ratio', es: 'Por Ratio M/O' },
  'targets.targetZ': { en: 'Target Z-score', es: 'Z-score objetivo' },
  'targets.targetSum6': { en: 'Target sum 6 skinfolds (mm)', es: 'Suma 6 pliegues objetivo (mm)' },
  'targets.targetRatio': { en: 'Target Muscle/Bone Ratio', es: 'Ratio Músculo/Óseo objetivo' },
  'targets.equivalentZ': { en: 'Equivalent Z:', es: 'Z equivalente:' },
  'targets.targetAdiposeMass': { en: 'Target adipose mass:', es: 'Masa adiposa objetivo:' },
  'targets.targetMuscleMass': { en: 'Target muscle mass:', es: 'Masa muscular objetivo:' },
  'targets.resultingMuscle': { en: 'Resulting muscle mass:', es: 'Masa muscular resultante:' },
  'targets.boneFixed': { en: 'bone', es: 'óseo' },
  'targets.changeSummary': { en: 'Change Summary', es: 'Resumen de cambios' },
  'targets.adiposeMassRow': { en: 'Adipose mass:', es: 'Masa adiposa:' },
  'targets.muscleMassRow': { en: 'Muscle mass:', es: 'Masa muscular:' },
  'targets.netChange': { en: 'Net body weight change:', es: 'Cambio neto de peso corporal:' },
  'targets.phantomNote': { en: '* Calculated based on the Phantom Reference (Ross & Ward, 1984). Bone and residual mass are considered fixed.', es: '* Calculado en base a la Referencia Fantasma (Ross & Ward, 1984). Masa ósea y residual se consideran fijas.' },
  'targets.noChange': { en: 'no change', es: 'sin cambio' },
  'targets.toGain': { en: 'to gain', es: 'a ganar' },
  'targets.toLose': { en: 'to lose', es: 'a perder' },

  'nav.dashboard': { en: 'Dashboard', es: 'Panel de Control' },
  'nav.athletes': { en: 'Athletes', es: 'Atletas' },
  'nav.evaluations': { en: 'Evaluations', es: 'Evaluaciones' },
  'nav.userManagement': { en: 'User Management', es: 'Gestión de Usuarios' },
  'nav.settings': { en: 'Settings', es: 'Configuración' },
  'nav.myProfile': { en: 'My Profile', es: 'Mi Perfil' },
  'nav.myEvaluations': { en: 'My Evaluations', es: 'Mis Evaluaciones' },
  'nav.anthropometry': { en: 'Anthropometry Lab', es: 'Lab Antropometría' },
  'nav.anthropometryDashboard': { en: 'Anthropometry Dashboard', es: 'Panel de Antropometría' },
  'nav.environmentalPhysiology': { en: 'Environmental Physiology', es: 'Fisiología Ambiental' },
  'nav.labSession': { en: 'Lab Session', es: 'Sesión de Laboratorio' },
  'nav.forceVelocity': { en: 'Force-Velocity Lab', es: 'Lab Fuerza-Velocidad' },
  'nav.referencePopulations': { en: 'Reference Populations', es: 'Poblaciones de Referencia' },
  'nav.reports': { en: 'Reports', es: 'Informes' },
  'nav.simulation': { en: 'Simulation', es: 'Simulación' },
  'nav.metabolicLab': { en: 'Metabolic Lab', es: 'Lab Metabólico' },
  'nav.hydrationHeat': { en: 'Hydration & Heat', es: 'Hidratación y Calor' },
  'nav.neuromuscularLab': { en: 'Neuromuscular Lab', es: 'Lab Neuromuscular' },
  'nav.biochemicalLab': { en: 'Biochemical Lab', es: 'Lab Bioquímico' },
  'nav.physiologyProfile': { en: 'Physiology Profile', es: 'Perfil Fisiológico' },
  'nav.healthFlags': { en: 'Health Flags', es: 'Alertas de Salud' },

  'athletes.title': { en: 'Athletes from HUB', es: 'Atletas del HUB' },
  'athletes.available': { en: 'available for testing', es: 'disponibles para evaluación' },
  'athletes.athlete': { en: 'athlete', es: 'atleta' },
  'athletes.athletes': { en: 'athletes', es: 'atletas' },
  'athletes.loading': { en: 'Loading athletes...', es: 'Cargando atletas...' },
  'athletes.error': { en: 'Error:', es: 'Error:' },
  'athletes.retry': { en: 'Retry', es: 'Reintentar' },
  'athletes.refresh': { en: 'Refresh', es: 'Actualizar' },
  'athletes.delete': { en: 'Delete athlete', es: 'Eliminar atleta' },
  'athletes.deleteTitle': { en: 'Delete Athlete', es: 'Eliminar Atleta' },
  'athletes.deleteConfirm': { en: 'Are you sure you want to permanently delete', es: '¿Estás seguro que querés eliminar permanentemente a' },
  'athletes.deleteWarning': { en: 'This action cannot be undone.', es: 'Esta acción no se puede deshacer.' },
  'athletes.confirmDelete': { en: 'Delete', es: 'Eliminar' },
  'athletes.deleting': { en: 'Deleting...', es: 'Eliminando...' },
  'athletes.cancel': { en: 'Cancel', es: 'Cancelar' },
  'athletes.notFound': { en: 'No athletes found in HUB', es: 'No se encontraron atletas en el HUB' },
  'athletes.notFoundDesc': { en: 'Athletes must be created in the main HUB system before running tests', es: 'Los atletas deben ser creados en el sistema HUB principal antes de realizar pruebas' },
  'athletes.years': { en: 'years', es: 'años' },
  'athletes.bodyFat': { en: 'Body Fat:', es: 'Grasa Corporal:' },
  'athletes.viewProfile': { en: 'View Profile', es: 'Ver Perfil' },
  'athletes.sport.cycling': { en: 'Cycling', es: 'Ciclismo' },
  'athletes.sport.running': { en: 'Running', es: 'Atletismo' },
  'athletes.sport.triathlon': { en: 'Triathlon', es: 'Triatlón' },
  'athletes.sport.swimming': { en: 'Swimming', es: 'Natación' },

  'steps.title': { en: 'Step', es: 'Paso' },
  'steps.basic': { en: 'Basic Measurements', es: 'Medidas Básicas' },
  'steps.skinfolds': { en: 'Skinfolds', es: 'Pliegues Cutáneos' },
  'steps.girths': { en: 'Girths/Perimeters', es: 'Perímetros' },
  'steps.lengths': { en: 'Lengths', es: 'Longitudes' },
  'steps.breadths': { en: 'Breadths/Diameters', es: 'Diámetros' },
  'steps.previous': { en: 'Previous', es: 'Anterior' },
  'steps.next': { en: 'Next', es: 'Siguiente' },
  'steps.save': { en: 'Save Measurement', es: 'Guardar Medición' },
  'steps.median': { en: 'Median:', es: 'Mediana:' },
  'steps.sd': { en: 'SD:', es: 'DE:' },
  'steps.error': { en: 'Error:', es: 'Error:' },

  'env.title': { en: 'Environmental Physiology', es: 'Fisiología Ambiental' },
  'env.subtitle': { en: 'Hydration, heat stress, and thermoregulation', es: 'Hidratación, estrés térmico y termorregulación' },
  'env.selectModule': { en: 'Select a module to begin assessment. Both modules share data to enable cross-analysis of hydration status and cardiac drift.', es: 'Selecciona un módulo para comenzar la evaluación. Ambos módulos comparten datos para análisis cruzado de estado de hidratación y deriva cardíaca.' },
  'env.hydrationLab': { en: 'Hydration Lab', es: 'Laboratorio de Hidratación' },
  'env.hydrationDesc': { en: 'Sweat rate, dehydration %, USG, and hydration stress score. Session-by-session tracking with environmental modifiers.', es: 'Tasa de sudoración, % deshidratación, DUE, e índice de estrés de hidratación. Seguimiento sesión a sesión con modificadores ambientales.' },
  'env.sweatRate': { en: 'Sweat Rate', es: 'Tasa de Sudoración' },
  'env.usg': { en: 'USG', es: 'DUE' },
  'env.hydrationStress': { en: 'Hydration Stress', es: 'Estrés de Hidratación' },
  'env.heatAdaptationLab': { en: 'Heat Adaptation Lab', es: 'Lab de Adaptación al Calor' },
  'env.heatDesc': { en: "Cardiac load, HR drift, adaptation score, and the Hydration-HR Drift coupling analysis to identify your athlete's true limiter.", es: 'Carga cardíaca, deriva de FC, puntuación de adaptación y análisis de acoplamiento Hidratación-Deriva FC para identificar el limitante real del atleta.' },
  'env.hrDrift': { en: 'HR Drift', es: 'Deriva FC' },
  'env.cardiacLoad': { en: 'Cardiac Load', es: 'Carga Cardíaca' },
  'env.hydrationCoupling': { en: 'Hydration Coupling', es: 'Acoplamiento de Hidratación' },
  'env.crossModule': { en: 'Cross-Module Intelligence', es: 'Inteligencia entre Módulos' },
  'env.crossModuleDesc': { en: "Once you have data in both modules, the Heat Adaptation Lab automatically cross-references hydration history to compute Corrected Drift and classify each session's primary limiter: Hydration vs. Aerobic Capacity.", es: 'Una vez que tengas datos en ambos módulos, el Lab de Adaptación al Calor cruza automáticamente el historial de hidratación para calcular la Deriva Corregida y clasificar el limitante principal de cada sesión: Hidratación vs. Capacidad Aeróbica.' },
  'env.backToEnv': { en: 'Back to Environmental Physiology', es: 'Volver a Fisiología Ambiental' },
  'env.selectAthlete': { en: 'Select Athlete', es: 'Seleccionar Atleta' },
  'env.changeAthlete': { en: 'Change athlete', es: 'Cambiar atleta' },

  'hydration.title': { en: 'Hydration & Thermoregulation Lab', es: 'Lab de Hidratación y Termorregulación' },
  'hydration.sessionsRecorded': { en: 'Sessions recorded:', es: 'Sesiones registradas:' },
  'hydration.avgSweatRate': { en: 'Avg sweat rate:', es: 'Tasa de sudoración prom.:' },
  'hydration.maxDehydration': { en: 'Max dehydration observed:', es: 'Máx. deshidratación observada:' },
  'hydration.sessionInfo': { en: 'Session Info', es: 'Info de Sesión' },
  'hydration.sessionDate': { en: 'Session Date', es: 'Fecha de Sesión' },
  'hydration.duration': { en: 'Duration (min) *', es: 'Duración (min) *' },
  'hydration.weightMeasurements': { en: 'Weight Measurements *', es: 'Medidas de Peso *' },
  'hydration.preWeight': { en: 'Pre-exercise Weight (kg)', es: 'Peso Pre-ejercicio (kg)' },
  'hydration.postWeight': { en: 'Post-exercise Weight (kg)', es: 'Peso Post-ejercicio (kg)' },
  'hydration.fluidBalance': { en: 'Fluid Balance', es: 'Balance de Fluidos' },
  'hydration.fluidIntake': { en: 'Fluid Intake (mL)', es: 'Ingesta de Fluidos (mL)' },
  'hydration.urineOutput': { en: 'Urine Output (mL)', es: 'Producción de Orina (mL)' },
  'hydration.usgSection': { en: 'Urine Specific Gravity (USG)', es: 'Densidad Urinaria Específica (DUE)' },
  'hydration.usgPre': { en: 'USG Pre-session', es: 'DUE Pre-sesión' },
  'hydration.usgPost': { en: 'USG Post-session', es: 'DUE Post-sesión' },
  'hydration.usgPreHint': { en: 'Baseline hydration status', es: 'Estado de hidratación basal' },
  'hydration.usgPostHint': { en: 'Post-exercise hydration status', es: 'Estado de hidratación post-ejercicio' },
  'hydration.envContext': { en: 'Environmental & Physiological Context', es: 'Contexto Ambiental y Fisiológico' },
  'hydration.temperature': { en: 'Temperature (°C)', es: 'Temperatura (°C)' },
  'hydration.humidity': { en: 'Humidity (%)', es: 'Humedad (%)' },
  'hydration.avgHR': { en: 'Avg HR (bpm)', es: 'FC Prom. (bpm)' },
  'hydration.rpe': { en: 'RPE (1–10)', es: 'RPE (1–10)' },
  'hydration.notes': { en: 'Notes', es: 'Notas' },
  'hydration.notesPlaceholder': { en: 'Optional notes about the session...', es: 'Notas opcionales sobre la sesión...' },
  'hydration.calculate': { en: 'Calculate Hydration Assessment', es: 'Calcular Evaluación de Hidratación' },
  'hydration.savedSuccess': { en: 'Hydration assessment saved and athlete profile updated.', es: 'Evaluación de hidratación guardada y perfil del atleta actualizado.' },
  'hydration.savedError': { en: 'Failed to save assessment. Please try again.', es: 'Error al guardar la evaluación. Por favor intenta de nuevo.' },
  'hydration.newSession': { en: 'New Session', es: 'Nueva Sesión' },
  'hydration.noSessions': { en: 'No sessions recorded yet.', es: 'Sin sesiones registradas aún.' },
  'hydration.noSessionsDesc': { en: 'Record your first hydration session to begin tracking.', es: 'Registra tu primera sesión de hidratación para comenzar el seguimiento.' },
  'hydration.recordFirst': { en: 'Record First Session', es: 'Registrar Primera Sesión' },
  'hydration.sweatRateLabel': { en: 'Sweat Rate', es: 'Tasa Sudoración' },
  'hydration.dehydration': { en: 'Dehydration', es: 'Deshidratación' },
  'hydration.stressScore': { en: 'Stress Score', es: 'Índice Estrés' },
  'hydration.saveSession': { en: 'Save Session', es: 'Guardar Sesión' },
  'hydration.saving': { en: 'Saving...', es: 'Guardando...' },
  'hydration.results': { en: 'Results', es: 'Resultados' },
  'hydration.history': { en: 'Session History', es: 'Historial de Sesiones' },

  'heat.title': { en: 'Heat Adaptation Tracking', es: 'Seguimiento de Adaptación al Calor' },
  'heat.sessions': { en: 'Sessions:', es: 'Sesiones:' },
  'heat.latestCardiacLoad': { en: 'Latest Cardiac Load:', es: 'Última Carga Cardíaca:' },
  'heat.latestHrDrift': { en: 'Latest HR Drift:', es: 'Última Deriva FC:' },
  'heat.adaptationScore': { en: 'Adaptation Score:', es: 'Puntuación de Adaptación:' },
  'heat.newSession': { en: 'New Session', es: 'Nueva Sesión' },
  'heat.adaptationTrends': { en: 'Adaptation Trends', es: 'Tendencias de Adaptación' },
  'heat.hydrationCoupling': { en: 'Hydration Coupling', es: 'Acoplamiento de Hidratación' },
  'heat.couplingTitle': { en: 'Hydration ↔ HR Drift Stability Analysis', es: 'Análisis de Estabilidad Hidratación ↔ Deriva FC' },
  'heat.couplingDesc': { en: 'Cross-references heat sessions with hydration history to identify whether HR drift is driven by dehydration or limited aerobic capacity.', es: 'Cruza sesiones de calor con historial de hidratación para identificar si la deriva FC se debe a deshidratación o capacidad aeróbica limitada.' },
  'heat.noHydrationSessions': { en: '— No hydration sessions found. Add sessions in Hydration Lab to enrich this analysis.', es: '— No se encontraron sesiones de hidratación. Agrega sesiones en el Lab de Hidratación para enriquecer este análisis.' },
  'heat.loading': { en: 'Loading...', es: 'Cargando...' },
  'heat.noSessions': { en: 'No sessions yet.', es: 'Sin sesiones aún.' },
  'heat.noSessionsDesc': { en: 'Record at least one heat session to see data here.', es: 'Registra al menos una sesión de calor para ver datos aquí.' },
  'heat.recordFirst': { en: 'Record First Session', es: 'Registrar Primera Sesión' },
  'heat.savedSuccess': { en: 'Heat session saved and adaptation profile updated.', es: 'Sesión de calor guardada y perfil de adaptación actualizado.' },
  'heat.savedError': { en: 'Failed to save session. Please try again.', es: 'Error al guardar la sesión. Por favor intenta de nuevo.' },
  'heat.sessionDate': { en: 'Session Date', es: 'Fecha de Sesión' },
  'heat.duration': { en: 'Duration (min)', es: 'Duración (min)' },
  'heat.sport': { en: 'Sport / Activity', es: 'Deporte / Actividad' },
  'heat.hrStart': { en: 'HR Start (bpm)', es: 'FC Inicio (bpm)' },
  'heat.hrEnd': { en: 'HR End (bpm)', es: 'FC Final (bpm)' },
  'heat.hrMax': { en: 'HR Max (bpm)', es: 'FC Máx (bpm)' },
  'heat.temperature': { en: 'Temperature (°C)', es: 'Temperatura (°C)' },
  'heat.humidity': { en: 'Humidity (%)', es: 'Humedad (%)' },
  'heat.rpe': { en: 'RPE (1–10)', es: 'RPE (1–10)' },
  'heat.notes': { en: 'Notes', es: 'Notas' },
  'heat.saveSession': { en: 'Save Session', es: 'Guardar Sesión' },
  'heat.saving': { en: 'Saving...', es: 'Guardando...' },
  'heat.cardiacLoad': { en: 'Cardiac Load', es: 'Carga Cardíaca' },
  'heat.hrDrift': { en: 'HR Drift', es: 'Deriva FC' },
  'heat.adaptScore': { en: 'Adapt. Score', es: 'Punt. Adapt.' },

  'fv.title': { en: 'Force-Velocity Lab', es: 'Lab Fuerza-Velocidad' },
  'fv.subtitle': { en: 'Research-grade F-V profiling from encoder, video, or manual data', es: 'Perfilado F-V de grado investigación desde encoder, video o datos manuales' },
  'fv.f0v0Profile': { en: 'F0 & V0 Profile', es: 'Perfil F0 & V0' },
  'fv.f0v0Desc': { en: 'Maximal theoretical force and velocity via linear regression', es: 'Fuerza y velocidad teórica máxima mediante regresión lineal' },
  'fv.pmaxCalc': { en: 'Pmax Calculation', es: 'Cálculo de Pmax' },
  'fv.pmaxDesc': { en: 'Peak power and optimal F-V operating point', es: 'Potencia pico y punto óptimo de operación F-V' },
  'fv.loadRec': { en: 'Load Recommendations', es: 'Recomendaciones de Carga' },
  'fv.loadRecDesc': { en: 'Precise weights per training stimulus from your curve', es: 'Pesos precisos por estímulo de entrenamiento desde tu curva' },
  'fv.selectAthlete': { en: 'Select an athlete to begin:', es: 'Selecciona un atleta para comenzar:' },
  'fv.sessionSetup': { en: 'Session Setup', es: 'Configuración de Sesión' },
  'fv.exercise': { en: 'Exercise', es: 'Ejercicio' },
  'fv.exerciseName': { en: 'Exercise name', es: 'Nombre del ejercicio' },
  'fv.sessionDate': { en: 'Session Date', es: 'Fecha de Sesión' },
  'fv.notesOptional': { en: 'Notes (optional)', es: 'Notas (opcional)' },
  'fv.notesPlaceholder': { en: 'Warm-up, conditions, athlete feedback...', es: 'Calentamiento, condiciones, retroalimentación del atleta...' },
  'fv.bodyMassFound': { en: 'Body mass from profile:', es: 'Masa corporal del perfil:' },
  'fv.bodyMassUsed': { en: '— used for force calculations', es: '— usada para cálculos de fuerza' },
  'fv.bodyMassDefault': { en: 'No body mass in athlete profile — will use 75 kg as default. Update the athlete profile for accurate results.', es: 'Sin masa corporal en el perfil del atleta — se usarán 75 kg por defecto. Actualiza el perfil del atleta para resultados precisos.' },
  'fv.startDataEntry': { en: 'Start Data Entry', es: 'Comenzar Ingreso de Datos' },
  'fv.changeAthlete': { en: 'Change athlete', es: 'Cambiar atleta' },
  'fv.changeSetup': { en: 'Change setup', es: 'Cambiar configuración' },
  'fv.dataEntry': { en: 'Data Entry', es: 'Ingreso de Datos' },
  'fv.dataEntryDesc': { en: 'Enter reps at different loads. The curve and recommendations update automatically as you add data.', es: 'Ingresa repeticiones con diferentes cargas. La curva y las recomendaciones se actualizan automáticamente al agregar datos.' },
  'fv.needMoreReps': { en: 'At least 2 valid reps at different loads are needed to compute the F-V curve. Add more loads.', es: 'Se necesitan al menos 2 repeticiones válidas con diferentes cargas para calcular la curva F-V. Agrega más cargas.' },
  'fv.tabCurve': { en: 'F-V Curve', es: 'Curva F-V' },
  'fv.tabRec': { en: 'Load Recommendations', es: 'Recomendaciones de Carga' },
  'fv.tabReps': { en: 'Rep Data', es: 'Datos de Reps' },
  'fv.tabHistory': { en: 'Session History', es: 'Historial de Sesiones' },
  'fv.fvCurve': { en: 'Force-Velocity Curve', es: 'Curva Fuerza-Velocidad' },
  'fv.exportCSV': { en: 'Export CSV', es: 'Exportar CSV' },
  'fv.noPrevSessions': { en: 'No previous sessions recorded for this athlete.', es: 'No hay sesiones anteriores registradas para este atleta.' },
  'fv.clickSession': { en: 'Click a session to overlay it on the F-V Curve tab.', es: 'Haz clic en una sesión para superponerla en la pestaña de Curva F-V.' },
  'fv.saving': { en: 'Saving to athlete profile...', es: 'Guardando en el perfil del atleta...' },
  'fv.save': { en: 'Save session to athlete profile', es: 'Guardar sesión en el perfil del atleta' },
  'fv.saved': { en: 'Session saved to athlete profile', es: 'Sesión guardada en el perfil del atleta' },
  'fv.fvProfile': { en: 'F-V Profile', es: 'Perfil F-V' },
  'fv.addLoad': { en: 'Add Load', es: 'Agregar Carga' },
  'fv.load': { en: 'Load (kg)', es: 'Carga (kg)' },
  'fv.velocity': { en: 'Mean Velocity (m/s)', es: 'Velocidad Media (m/s)' },
  'fv.reps': { en: 'Reps', es: 'Reps' },
  'fv.best': { en: 'Best', es: 'Mejor' },
  'fv.delete': { en: 'Delete', es: 'Eliminar' },
  'fv.noReps': { en: 'No rep data yet. Add loads above to begin.', es: 'Sin datos de reps aún. Agrega cargas arriba para comenzar.' },

  'lab.title': { en: 'Metabolic Lab', es: 'Laboratorio Metabólico' },
  'lab.subtitle': { en: 'Guided physiological assessment workflow', es: 'Flujo de trabajo de evaluación fisiológica guiado' },
  'lab.step1': { en: 'Step 1 — Select Athlete', es: 'Paso 1 — Seleccionar Atleta' },
  'lab.step2': { en: 'Step 2 — Select Sport', es: 'Paso 2 — Seleccionar Deporte' },
  'lab.step3': { en: 'Step 3 — Select Test Protocol', es: 'Paso 3 — Seleccionar Protocolo de Prueba' },
  'lab.newAthlete': { en: 'New Athlete', es: 'Nuevo Atleta' },
  'lab.cancel': { en: 'Cancel', es: 'Cancelar' },
  'lab.createSelect': { en: 'Create & Select', es: 'Crear y Seleccionar' },
  'lab.creating': { en: 'Creating...', es: 'Creando...' },
  'lab.createNewProfile': { en: 'Create a new athlete profile for this session', es: 'Crear un nuevo perfil de atleta para esta sesión' },
  'lab.fullName': { en: 'Full Name *', es: 'Nombre Completo *' },
  'lab.fullNamePlaceholder': { en: "Athlete's full name", es: 'Nombre completo del atleta' },
  'lab.dateOfBirth': { en: 'Date of Birth', es: 'Fecha de Nacimiento' },
  'lab.biologicalSex': { en: 'Biological Sex', es: 'Sexo Biológico' },
  'lab.notSpecified': { en: 'Not specified', es: 'No especificado' },
  'lab.male': { en: 'Male', es: 'Masculino' },
  'lab.female': { en: 'Female', es: 'Femenino' },
  'lab.weight': { en: 'Weight (kg)', es: 'Peso (kg)' },
  'lab.height': { en: 'Height (cm)', es: 'Talla (cm)' },
  'lab.bodyFat': { en: 'Body Fat (%)', es: 'Grasa Corporal (%)' },
  'lab.searchAthletes': { en: 'Search athletes...', es: 'Buscar atletas...' },
  'lab.loadingAthletes': { en: 'Loading athletes...', es: 'Cargando atletas...' },
  'lab.noAthletes': { en: 'No athletes found.', es: 'No se encontraron atletas.' },
  'lab.createOne': { en: 'Create one', es: 'Crear uno' },
  'lab.numStages': { en: 'Number of Stages', es: 'Número de Etapas' },
  'lab.typicalStages': { en: 'Typical: 5–10', es: 'Típico: 5–10' },
  'lab.stageDuration': { en: 'Stage Duration (seconds)', es: 'Duración de Etapa (segundos)' },
  'lab.typicalDuration': { en: 'Typical: 180–300 s', es: 'Típico: 180–300 s' },
  'lab.includeCooldown': { en: 'Include Cool Down stage', es: 'Incluir etapa de enfriamiento' },
  'lab.customProtocol': { en: 'Custom per-stage durations', es: 'Duraciones personalizadas por etapa' },
  'lab.durationPerStage': { en: 'Duration per stage (seconds) — set partial time for last completed stage', es: 'Duración por etapa (segundos) — establece tiempo parcial para la última etapa completada' },
  'lab.partialTip': { en: 'Tip: use a shorter time for the last stage the athlete could not complete in full', es: 'Consejo: usa un tiempo menor para la última etapa que el atleta no pudo completar' },
  'lab.skipPretest': { en: 'Skip Pre-Test Checklist', es: 'Omitir Lista de Pre-Prueba' },
  'lab.skipPretestDesc': { en: 'Go directly to data entry if pre-test conditions were already recorded', es: 'Ir directamente al ingreso de datos si las condiciones pre-prueba ya fueron registradas' },
  'lab.startSession': { en: 'Start Guided Lab Session →', es: 'Iniciar Sesión de Lab Guiada →' },
  'lab.sport.cycling': { en: 'Cycling', es: 'Ciclismo' },
  'lab.sport.running': { en: 'Running', es: 'Atletismo' },
  'lab.sport.triathlon': { en: 'Triathlon', es: 'Triatlón' },
  'lab.sport.swimming': { en: 'Swimming', es: 'Natación' },

  'pretest.title': { en: 'Pre-Test Checklist', es: 'Lista de Pre-Prueba' },
  'pretest.lastProfile': { en: 'Last Physiological Profile', es: 'Último Perfil Fisiológico' },
  'pretest.lastUpdated': { en: 'Last updated:', es: 'Última actualización:' },
  'pretest.autoLoaded': { en: 'Auto-loaded from profile', es: 'Cargado automáticamente del perfil' },
  'pretest.anthropometry': { en: 'Anthropometry', es: 'Antropometría' },
  'pretest.weightRequired': { en: 'Weight (kg) *', es: 'Peso (kg) *' },
  'pretest.heightRequired': { en: 'Height (cm) *', es: 'Talla (cm) *' },
  'pretest.bodyFat': { en: 'Body Fat (%)', es: 'Grasa Corporal (%)' },
  'pretest.lbm': { en: 'Lean Body Mass (calculated):', es: 'Masa Corporal Magra (calculada):' },
  'pretest.preExerciseStatus': { en: 'Pre-Exercise Status', es: 'Estado Pre-Ejercicio' },
  'pretest.preExerciseDesc': { en: 'Optional — used for heat and hydration analysis', es: 'Opcional — usado para análisis de calor e hidratación' },
  'pretest.restingHR': { en: 'Resting HR (bpm)', es: 'FC en Reposo (bpm)' },
  'pretest.hrv': { en: 'HRV (ms)', es: 'VFC (ms)' },
  'pretest.usg': { en: 'USG (urine)', es: 'DUE (orina)' },
  'pretest.basalLactate': { en: 'Basal Lactate (mmol/L)', es: 'Lactato Basal (mmol/L)' },
  'pretest.basalLactateHint': { en: 'Resting venous baseline', es: 'Baseline venoso en reposo' },
  'pretest.rmr': { en: 'RMR (kcal/day)', es: 'TMB (kcal/día)' },
  'pretest.rmrHint': { en: 'Resting metabolic rate (if known)', es: 'Tasa metabólica en reposo (si se conoce)' },
  'pretest.envConditions': { en: 'Environmental Conditions', es: 'Condiciones Ambientales' },
  'pretest.envDesc': { en: 'Optional — used for heat adaptation scoring', es: 'Opcional — usado para puntuación de adaptación al calor' },
  'pretest.temperature': { en: 'Temperature (°C)', es: 'Temperatura (°C)' },
  'pretest.humidity': { en: 'Humidity (%)', es: 'Humedad (%)' },
  'pretest.back': { en: 'Back', es: 'Atrás' },
  'pretest.skip': { en: 'Skip →', es: 'Omitir →' },
  'pretest.confirm': { en: 'Confirm & Begin Test →', es: 'Confirmar e Iniciar Prueba →' },
  'pretest.loadingData': { en: 'Loading athlete data...', es: 'Cargando datos del atleta...' },

  'stages.title': { en: 'Stage Data Entry', es: 'Ingreso de Datos de Etapas' },
  'stages.preparing': { en: 'Preparing test session...', es: 'Preparando sesión de prueba...' },
  'stages.failed': { en: 'Failed to create test session.', es: 'Error al crear la sesión de prueba.' },
  'stages.retry': { en: 'Retry', es: 'Reintentar' },
  'stages.weight': { en: 'Weight:', es: 'Peso:' },
  'stages.height': { en: 'Height:', es: 'Talla:' },
  'stages.temp': { en: 'Temp:', es: 'Temp:' },
  'stages.humidity': { en: 'Humidity:', es: 'Humedad:' },
  'stages.hrRest': { en: 'HR rest:', es: 'FC reposo:' },

  'processing.title': { en: 'Analyzing Lab Data', es: 'Analizando Datos de Laboratorio' },
  'processing.subtitle': { en: 'Please wait while we process your results', es: 'Por favor espera mientras procesamos tus resultados' },
  'processing.step1': { en: 'Loading test data', es: 'Cargando datos de prueba' },
  'processing.step2': { en: 'Calculating VO\u2082max', es: 'Calculando VO\u2082max' },
  'processing.step3': { en: 'Identifying LT1 & LT2', es: 'Identificando LT1 y LT2' },
  'processing.step4': { en: 'Computing FatMax & energy profile', es: 'Calculando FatMax y perfil energético' },
  'processing.step5': { en: 'Calculating movement economy', es: 'Calculando economía de movimiento' },
  'processing.step6': { en: 'Analyzing HR drift & recovery', es: 'Analizando deriva FC y recuperación' },
  'processing.step7': { en: 'Building training zones', es: 'Construyendo zonas de entrenamiento' },
  'processing.step8': { en: 'Syncing athlete profile', es: 'Sincronizando perfil del atleta' },
  'processing.error': { en: 'An error occurred during processing. Please try again.', es: 'Ocurrió un error durante el procesamiento. Por favor intenta de nuevo.' },

  'results.title': { en: 'Physiological Snapshot', es: 'Instantánea Fisiológica' },
  'results.hideManual': { en: 'Hide Manual Input', es: 'Ocultar Entrada Manual' },
  'results.showManual': { en: 'Manual Input (VO\u2082 Master)', es: 'Entrada Manual (VO\u2082 Master)' },
  'results.manualTitle': { en: 'Manual Entry — VO\u2082 Master / External Device', es: 'Entrada Manual — VO\u2082 Master / Dispositivo Externo' },
  'results.manualDesc': { en: 'Enter results directly from your device. Zones will be built automatically from thresholds.', es: 'Ingresa los resultados directamente desde tu dispositivo. Las zonas se construirán automáticamente desde los umbrales.' },
  'results.applyManual': { en: 'Apply Manual Results →', es: 'Aplicar Resultados Manuales →' },
  'results.coreMarkers': { en: 'Core Physiological Markers', es: 'Marcadores Fisiológicos Principales' },
  'results.advancedMetrics': { en: 'Advanced Metrics', es: 'Métricas Avanzadas' },
  'results.advancedDesc': { en: 'Energy profile, recovery, economy, anaerobic', es: 'Perfil energético, recuperación, economía, anaeróbico' },
  'results.applyZones': { en: 'Apply Zones to Athlete Profile →', es: 'Aplicar Zonas al Perfil del Atleta →' },
  'results.vo2measured': { en: 'VO\u2082 measured', es: 'VO\u2082 medido' },
  'results.lactate': { en: 'Lactate', es: 'Lactato' },
  'results.power': { en: 'Power', es: 'Potencia' },

  'apply.title': { en: 'Apply to Athlete Profile', es: 'Aplicar al Perfil del Atleta' },
  'apply.currentZones': { en: 'Current Zones', es: 'Zonas Actuales' },
  'apply.newZones': { en: 'New Physiology Zones', es: 'Nuevas Zonas Fisiológicas' },
  'apply.noZones': { en: 'No zones calculated', es: 'Sin zonas calculadas' },
  'apply.updateOptions': { en: 'Update Options', es: 'Opciones de Actualización' },
  'apply.applyZones': { en: 'Apply physiology zones to athlete profile', es: 'Aplicar zonas fisiológicas al perfil del atleta' },
  'apply.applyZonesDesc': { en: 'Replaces current zones with zones derived from this test', es: 'Reemplaza las zonas actuales con zonas derivadas de esta prueba' },
  'apply.lockZones': { en: 'Lock zones to physiology', es: 'Bloquear zonas a fisiología' },
  'apply.lockZonesDesc': { en: 'Prevents manual editing until next lab session', es: 'Impide la edición manual hasta la próxima sesión de laboratorio' },
  'apply.zonesNotUpdated': { en: 'Zones will not be updated. Current zones remain unchanged.', es: 'Las zonas no se actualizarán. Las zonas actuales permanecen sin cambios.' },
  'apply.backToResults': { en: 'Back to Results', es: 'Volver a Resultados' },
  'apply.confirmUpdate': { en: 'Confirm Update →', es: 'Confirmar Actualización →' },
  'apply.updating': { en: 'Updating...', es: 'Actualizando...' },

  'report.title': { en: 'Generate Report', es: 'Generar Informe' },
  'report.sessionSummary': { en: 'Session Summary', es: 'Resumen de Sesión' },
  'report.selectType': { en: 'Select Report Type', es: 'Seleccionar Tipo de Informe' },
  'report.scientific': { en: 'Full Scientific Report', es: 'Informe Científico Completo' },
  'report.scientificDesc': { en: 'Complete analysis: VO\u2082, thresholds, energy profile, hydration, graphs, longitudinal comparison', es: 'Análisis completo: VO\u2082, umbrales, perfil energético, hidratación, gráficos, comparación longitudinal' },
  'report.coach': { en: 'Coach Summary', es: 'Resumen para Entrenador' },
  'report.coachDesc': { en: 'Training zones, thresholds, key metrics, and actionable recommendations', es: 'Zonas de entrenamiento, umbrales, métricas clave y recomendaciones accionables' },
  'report.athlete': { en: 'Athlete Friendly', es: 'Para el Atleta' },
  'report.athleteDesc': { en: 'Simple summary with zones, fitness level, and easy-to-understand insights', es: 'Resumen simple con zonas, nivel de condición física e insights fáciles de entender' },
  'report.exportJSON': { en: 'Export JSON', es: 'Exportar JSON' },
  'report.newSession': { en: 'New Lab Session', es: 'Nueva Sesión de Lab' },
  'report.generate': { en: 'Generate Report', es: 'Generar Informe' },
  'report.generating': { en: 'Generating...', es: 'Generando...' },

  'reports.pageTitle': { en: 'Reports', es: 'Informes' },
  'reports.selectAthlete': { en: 'Select an athlete to generate a report', es: 'Seleccioná un atleta para generar un informe' },
  'reports.selectTest': { en: 'Select Test Session', es: 'Seleccionar Sesión de Prueba' },
  'reports.selectTestDesc': { en: 'Choose which test to include in the report, or build an athlete-only report', es: 'Elegí qué prueba incluir en el informe, o generá un informe solo de perfil del atleta' },
  'reports.athleteProfileOnly': { en: 'Athlete Profile Only', es: 'Solo Perfil del Atleta' },
  'reports.athleteProfileDesc': { en: 'Anthropometry and hydration data, without a lab session', es: 'Datos de antropometría e hidratación, sin sesión de laboratorio' },
  'reports.noTests': { en: 'No completed lab sessions found', es: 'No se encontraron sesiones de laboratorio completadas' },

  'reportBuilder.title': { en: 'Report Builder', es: 'Constructor de Informes' },
  'reportBuilder.typeSection': { en: 'A — Report Type', es: 'A — Tipo de Informe' },
  'reportBuilder.typeDesc': { en: 'Select a preset or build custom', es: 'Seleccioná un preset o armá uno personalizado' },
  'reportBuilder.sectionsSection': { en: 'B — Sections', es: 'B — Secciones' },
  'reportBuilder.selected': { en: 'selected', es: 'seleccionadas' },
  'reportBuilder.all': { en: 'All', es: 'Todas' },
  'reportBuilder.none': { en: 'None', es: 'Ninguna' },
  'reportBuilder.styleSection': { en: 'C — Report Style', es: 'C — Estilo del Informe' },
  'reportBuilder.branding': { en: 'Branding', es: 'Identidad' },
  'reportBuilder.brandingDesc': { en: 'Appears on cover page & footer', es: 'Aparece en la portada y el pie de página' },
  'reportBuilder.labName': { en: 'Lab / Organization Name', es: 'Lab / Nombre de Organización' },
  'reportBuilder.labNamePlaceholder': { en: 'e.g. Performance Lab', es: 'ej. Asciende Metabolic Lab' },
  'reportBuilder.evaluatorName': { en: 'Evaluator Name', es: 'Nombre del Evaluador' },
  'reportBuilder.evaluatorPlaceholder': { en: 'e.g. Dr. Jane Smith', es: 'ej. Dr. Juan Pérez' },
  'reportBuilder.credentials': { en: 'Credentials', es: 'Credenciales' },
  'reportBuilder.credentialsPlaceholder': { en: 'e.g. MSc, ISAK L2', es: 'ej. Lic. Cs. del Deporte, ISAK N2' },
  'reportBuilder.contactInfo': { en: 'Contact Info', es: 'Información de Contacto' },
  'reportBuilder.contactPlaceholder': { en: 'e.g. email / phone / website', es: 'ej. email / teléfono / web' },
  'reportBuilder.generating': { en: 'Generating PDF...', es: 'Generando PDF...' },
  'reportBuilder.generate': { en: 'Generate PDF', es: 'Generar PDF' },
  'reportBuilder.sections': { en: 'sections', es: 'secciones' },
  'reportBuilder.noSections': { en: 'Select at least one section to generate the report', es: 'Seleccioná al menos una sección para generar el informe' },
  'reportBuilder.noData': { en: 'no data', es: 'sin datos' },

  'reportType.full': { en: 'Full Performance', es: 'Rendimiento Completo' },
  'reportType.fullDesc': { en: 'All available data — physiology, anthropometry, hydration, recommendations', es: 'Todos los datos disponibles — fisiología, antropometría, hidratación, recomendaciones' },
  'reportType.lab': { en: 'Lab Session', es: 'Sesión de Lab' },
  'reportType.labDesc': { en: 'VO\u2082max, thresholds, zones, economy, raw data', es: 'VO\u2082max, umbrales, zonas, economía, datos crudos' },
  'reportType.anthropometry': { en: 'Anthropometry', es: 'Antropometría' },
  'reportType.anthropometryDesc': { en: 'Body composition, ISAK measurements, reference comparison', es: 'Composición corporal, medidas ISAK, comparación de referencia' },
  'reportType.hydration': { en: 'Hydration', es: 'Hidratación' },
  'reportType.hydrationDesc': { en: 'Sweat rate, dehydration, hydration sessions history', es: 'Tasa de sudoración, deshidratación, historial de sesiones' },
  'reportType.comparative': { en: 'Comparative', es: 'Comparativo' },
  'reportType.comparativeDesc': { en: 'Body composition vs. reference population norms', es: 'Composición corporal vs. normas de población de referencia' },
  'reportType.custom': { en: 'Custom', es: 'Personalizado' },
  'reportType.customDesc': { en: 'Select exactly which sections to include', es: 'Seleccioná exactamente qué secciones incluir' },

  'reportStyle.scientific': { en: 'Scientific Detailed', es: 'Científico Detallado' },
  'reportStyle.scientificDesc': { en: 'Full methodology, confidence levels, derived indices, all stats', es: 'Metodología completa, niveles de confianza, índices derivados, todas las estadísticas' },
  'reportStyle.coach': { en: 'Coach Summary', es: 'Resumen para Entrenador' },
  'reportStyle.coachDesc': { en: 'Key numbers, zones, actionable insights — no excessive detail', es: 'Números clave, zonas, insights accionables — sin exceso de detalle' },
  'reportStyle.athlete': { en: 'Athlete Friendly', es: 'Para el Atleta' },
  'reportStyle.athleteDesc': { en: 'Simple language, visual emphasis, no scientific jargon', es: 'Lenguaje simple, énfasis visual, sin jerga científica' },
  'reportStyle.minimal': { en: 'Minimal', es: 'Mínimo' },
  'reportStyle.minimalDesc': { en: 'Essential numbers only, clean and concise', es: 'Solo números esenciales, limpio y conciso' },

  'reportSection.cover': { en: 'Cover Page', es: 'Portada' },
  'reportSection.executive_summary': { en: 'Executive Summary', es: 'Resumen Ejecutivo' },
  'reportSection.anthropometry': { en: 'Body Composition (Kerr)', es: 'Composición Corporal (Kerr)' },
  'reportSection.isak_details': { en: 'ISAK Measurement Details', es: 'Detalle de Medidas ISAK' },
  'reportSection.anthropometry_comparison': { en: 'Anthropometry Comparison', es: 'Comparación Antropométrica' },
  'reportSection.vo2max': { en: 'VO\u2082max', es: 'VO\u2082max' },
  'reportSection.thresholds': { en: 'Lactate Thresholds (LT1 / LT2)', es: 'Umbrales de Lactato (LT1 / LT2)' },
  'reportSection.fat_oxidation': { en: 'Fat Oxidation & FatMax', es: 'Oxidación de Grasas y FatMax' },
  'reportSection.training_zones': { en: 'Training Zones', es: 'Zonas de Entrenamiento' },
  'reportSection.economy_metrics': { en: 'Economy & Power Metrics', es: 'Economía y Métricas de Potencia' },
  'reportSection.hydration': { en: 'Hydration Analysis', es: 'Análisis de Hidratación' },
  'reportSection.heat_adaptation': { en: 'Heat Adaptation Notes', es: 'Notas de Adaptación al Calor' },
  'reportSection.raw_data': { en: 'Appendix: Raw Stage Data', es: 'Apéndice: Datos de Etapas' },
  'reportSection.recommendations': { en: 'Recommendations', es: 'Recomendaciones' },

  'reportGroup.General': { en: 'General', es: 'General' },
  'reportGroup.Anthropometry': { en: 'Anthropometry', es: 'Antropometría' },
  'reportGroup.Physiology': { en: 'Physiology', es: 'Fisiología' },
  'reportGroup.Environmental': { en: 'Environmental', es: 'Ambiental' },
  'reportGroup.Data': { en: 'Data', es: 'Datos' },
  'reportGroup.Conclusions': { en: 'Conclusions', es: 'Conclusiones' },

  'workflow.exit': { en: 'Exit', es: 'Salir' },
  'workflow.selection': { en: 'Selection', es: 'Selección' },
  'workflow.preTest': { en: 'Pre-Test', es: 'Pre-Prueba' },
  'workflow.dataEntry': { en: 'Data Entry', es: 'Ingreso de Datos' },
  'workflow.processing': { en: 'Processing', es: 'Procesando' },
  'workflow.results': { en: 'Results', es: 'Resultados' },
  'workflow.apply': { en: 'Apply', es: 'Aplicar' },
  'workflow.report': { en: 'Report', es: 'Informe' },

  'sim.athlete': { en: 'Athlete', es: 'Atleta' },
  'sim.selectAthlete': { en: '-- Select athlete --', es: '-- Seleccionar atleta --' },
  'sim.loadingProfile': { en: 'Loading profile...', es: 'Cargando perfil...' },
  'sim.weight': { en: 'Weight', es: 'Peso' },
  'sim.vo2maxEdit': { en: 'VO2max (edit)', es: 'VO2max (editar)' },
  'sim.orEnterVO2max': { en: 'Or enter VO2max directly:', es: 'O ingresa VO2max directamente:' },
  'sim.raceParams': { en: 'Race Parameters', es: 'Parámetros de la Carrera' },
  'sim.distance': { en: 'Distance', es: 'Distancia' },
  'sim.targetPace': { en: 'Target pace (min:sec/km)', es: 'Ritmo objetivo (min:seg/km)' },
  'sim.terrain': { en: 'Terrain', es: 'Terreno' },
  'sim.raceStrategy': { en: 'Race strategy', es: 'Estrategia de carrera' },
  'sim.temperature': { en: 'Temperature', es: 'Temperatura' },
  'sim.humidity': { en: 'Humidity', es: 'Humedad' },
  'sim.altitude': { en: 'Altitude (m asl)', es: 'Altitud (m s.n.m.)' },
  'sim.simulate': { en: 'Simulate Race', es: 'Simular Carrera' },
  'sim.saving': { en: 'Saving...', es: 'Guardando...' },
  'sim.saved': { en: 'Saved!', es: '¡Guardado!' },
  'sim.save': { en: 'Save', es: 'Guardar' },
  'sim.projectedTime': { en: 'Projected time', es: 'Tiempo proyectado' },
  'sim.avgHR': { en: 'Avg HR', es: 'FC promedio' },
  'sim.kcalCost': { en: 'kcal cost', es: 'Coste kcal' },
  'sim.carbs': { en: 'Carbs', es: 'Hidratos' },
  'sim.fats': { en: 'Fats', es: 'Grasas' },
  'sim.dehydration': { en: 'Dehydration', es: 'Deshidratación' },
  'sim.runningEconomy': { en: 'Running economy', es: 'Ec. de carrera' },
  'sim.bonkRisk': { en: 'Bonk risk', es: 'Riesgo bonk' },
  'sim.glycogen': { en: 'glycogen', es: 'glucógeno' },
  'sim.animatedProgress': { en: 'Animated Race Progress', es: 'Progreso Animado de la Carrera' },
  'sim.pause': { en: 'Pause', es: 'Pausar' },
  'sim.repeat': { en: 'Repeat', es: 'Repetir' },
  'sim.play': { en: 'Play', es: 'Play' },
  'sim.currentKm': { en: 'Current km', es: 'Km actual' },
  'sim.pace': { en: 'Pace', es: 'Ritmo' },
  'sim.hr': { en: 'HR', es: 'FC' },
  'sim.fatigue': { en: 'Fatigue', es: 'Fatiga' },
  'sim.accumulated': { en: 'accumulated', es: 'acumulada' },
  'sim.paceHR': { en: 'Pace / HR', es: 'Ritmo / FC' },
  'sim.lactate': { en: 'Lactate', es: 'Lactato' },
  'sim.zones': { en: 'Zones', es: 'Zonas' },
  'sim.strategy': { en: 'Strategy', es: 'Estrategia' },
  'sim.glycogenTab': { en: 'Glycogen', es: 'Glucógeno' },
  'sim.glycogenRemaining': { en: 'Remaining glycogen', es: 'Glucógeno restante' },
  'sim.timeInZone': { en: 'Time in zone', es: 'Tiempo en zona' },
  'sim.zoneDistribution': { en: 'Estimated time distribution by zone', es: 'Distribución estimada de tiempo por zona' },
  'sim.glycogenEstimate': { en: 'Estimated muscle glycogen reserves during the race', es: 'Reservas de glucógeno muscular estimadas durante la carrera' },
  'sim.lactateEstimate': { en: 'Estimated blood lactate accumulation', es: 'Acumulación estimada de lactato en sangre' },
  'sim.execRecommendations': { en: 'Execution Recommendations', es: 'Recomendaciones de Ejecución' },
  'sim.selected': { en: 'Selected', es: 'Seleccionada' },
  'sim.start': { en: 'Start', es: 'Salida' },
  'sim.finish': { en: 'Finish', es: 'Meta' },

  'sim.dist.track1k': { en: '1K (track)', es: '1K (pista)' },
  'sim.dist.halfMarathon': { en: 'Half Marathon (21K)', es: 'Media Maratón (21K)' },
  'sim.dist.marathon': { en: 'Marathon (42K)', es: 'Maratón (42K)' },
  'sim.dist.trail50': { en: '50K Trail', es: '50K Trail' },
  'sim.dist.ultra100': { en: '100K Ultra', es: '100K Ultra' },
  'sim.dist.custom': { en: 'Custom', es: 'Personalizada' },

  'sim.terrain.flat': { en: 'Flat', es: 'Llano' },
  'sim.terrain.rolling': { en: 'Rolling', es: 'Ondulado' },
  'sim.terrain.hilly': { en: 'Hilly', es: 'Montañoso' },

  'sim.strategy.even': { en: 'Even', es: 'Uniforme' },
  'sim.strategy.evenDesc': { en: 'Constant pace start to finish', es: 'Ritmo constante de inicio a fin' },
  'sim.strategy.negative': { en: 'Negative split', es: 'Negativo' },
  'sim.strategy.negativeDesc': { en: 'Conservative start, accelerates at end', es: 'Salida conservadora, acelera al final' },
  'sim.strategy.positive': { en: 'Positive split', es: 'Positivo' },
  'sim.strategy.positiveDesc': { en: 'Fast start, holds to finish', es: 'Salida rápida, resiste hasta meta' },

  'sim.feasibility.optimal': { en: 'Optimal', es: 'Óptimo' },
  'sim.feasibility.challenging': { en: 'Challenging', es: 'Desafiante' },
  'sim.feasibility.limit': { en: 'At the limit', es: 'En el límite' },
  'sim.feasibility.impossible': { en: 'Beyond capacity', es: 'Fuera de capacidad' },

  'sim.profile.lt1Hr': { en: 'LT1', es: 'LT1' },
  'sim.profile.lt2Hr': { en: 'LT2', es: 'LT2' },
  'sim.profile.lt2Pace': { en: 'LT2 Pace', es: 'Ritmo LT2' },
  'sim.profile.hrMax': { en: 'HRmax', es: 'FCmax' },
  'sim.profile.re': { en: 'RE', es: 'RE' },

  'sim.risk.vo2maxCritical': { en: 'Pace demands >95% VO2max — risk of early collapse', es: 'Ritmo exige más del 95% del VO2max — riesgo de colapso precoz' },
  'sim.risk.vo2maxHigh': { en: 'Very high intensity (>88% VO2max) — lactate accumulation likely', es: 'Intensidad muy alta (>88% VO2max) — acumulación de lactato probable' },
  'sim.risk.dehydrationWarning': { en: 'Estimated dehydration __PERCENT__% — performance compromised', es: 'Deshidratación estimada __PERCENT__% — rendimiento comprometido' },
  'sim.risk.dehydrationDanger': { en: 'Critical dehydration (>5%) — risk of heat stroke', es: 'Deshidratación crítica (>5%) — riesgo de golpe de calor' },
  'sim.risk.carbsHigh': { en: 'CHO expenditure __CARBS__g — plan race intake', es: 'Gasto de CHO __CARBS__g — planificar ingesta en carrera' },
  'sim.risk.altitudeVO2': { en: 'Altitude __ALT__m reduces VO2max ~__PCT__%', es: 'Altitud __ALT__m reduce VO2max ~__PCT__% ' },
  'sim.risk.extremeTemp': { en: 'Extreme temperature (>30°C) — high thermal stress', es: 'Temperatura extrema (>30°C) — alto estrés térmico' },
  'sim.risk.bonk': { en: 'Estimated bonk at km __KM__ — glycogen depleted without carb intake', es: 'Bonk estimado en km __KM__ — glucógeno agotado sin ingesta' },
  'sim.risk.positiveStrategy': { en: 'Fast-start strategy — early lactate accumulation may compromise the second half', es: 'Estrategia de salida rápida — acumulación de lactato temprana puede comprometer la segunda mitad' },

  'sim.rec.reducePace': { en: 'Consider reducing target pace 3-5% to stay in a sustainable zone', es: 'Considera reducir el ritmo objetivo un 3-5% para estar en zona sostenible' },
  'sim.rec.drink': { en: 'Drink ~__ML__ml every 15 min to compensate sweating', es: 'Beber ~__ML__ml cada 15 min para compensar sudoración' },
  'sim.rec.carbIntake': { en: 'Race carb intake: ~__RATE__g/h recommended', es: 'Ingesta de CHO durante carrera: ~__RATE__g/h recomendados' },
  'sim.rec.acclimatize': { en: '10-14 day acclimatization before competing at this altitude', es: 'Aclimatación de 10-14 días antes de competir en esta altitud' },
  'sim.rec.precooling': { en: 'Pre-cooling (ice vest) and pace adjustment in first 5km in heat', es: 'Pre-cooling (chaleco de frío) y ajuste de ritmo primeros 5km en calor' },
  'sim.rec.gels': { en: 'Consume gel/carbs every 30-40 min to prevent bonk (estimated km __KM__)', es: 'Consumir gel/CHO cada 30-40 min para prevenir bonk (estimado km __KM__)' },
  'sim.rec.runningEconomy': { en: 'Estimated running economy: __RE__ ml O2/kg/km — work technique to improve to <210', es: 'Economía de carrera estimada: __RE__ ml O2/kg/km — trabajar técnica para mejorarla a <210' },
  'sim.rec.negativeStrategy': { en: 'Conservative start — gradually accelerate in the second half when rivals struggle', es: 'Estrategia de salida conservadora — acelera gradualmente en la segunda mitad cuando los rivales sufren' },
  'sim.rec.allGood': { en: 'Physiological profile compatible with the goal — execution with safety margin', es: 'Perfil fisiológico compatible con el objetivo — ejecución con margen de seguridad' },
  'sim.rec.bonkGlycogenOk': { en: 'Sufficient glycogen reserves to complete the distance without mandatory intake.', es: 'Reservas de glucógeno suficientes para completar la distancia sin ingesta obligatoria.' },

  'sim.altitude.seaLevel': { en: 'Sea level', es: 'Nivel del mar' },
  'sim.altitude.seaLevelEffects': { en: 'No significant effect on aerobic performance', es: 'Sin efecto significativo en rendimiento aeróbico' },
  'sim.altitude.low': { en: 'Low altitude', es: 'Altitud baja' },
  'sim.altitude.lowEffects': { en: 'Slight VO2max reduction, rapid adaptation (5-7 days)', es: 'Ligera reducción de VO2max, adaptación rápida (5-7 días)' },
  'sim.altitude.medium': { en: 'Moderate altitude', es: 'Altitud media' },
  'sim.altitude.mediumEffects': { en: 'Significant hypoxia, increased ventilation, elevated HR', es: 'Hipoxia significativa, mayor ventilación, HR elevada' },
  'sim.altitude.high': { en: 'High altitude', es: 'Altitud alta' },
  'sim.altitude.highEffects': { en: 'High physiological stress, risk of altitude sickness', es: 'Alto estrés fisiológico, riesgo de mal de montaña' },
  'sim.altitude.deathZone': { en: 'Death zone', es: 'Zona de muerte' },
  'sim.altitude.deathZoneEffects': { en: 'Progressive deterioration, complete acclimatization impossible', es: 'Deterioro progresivo, imposible aclimatación completa' },

  'sim.altitude.risk.moderate': { en: 'Moderate altitude — allow 5-7 days of acclimatization before hard training', es: 'Altitud moderada — esperar 5-7 días de aclimatación antes de entrenar fuerte' },
  'sim.altitude.risk.ams': { en: 'Risk of Acute Mountain Sickness (AMS) — mandatory gradual ascent', es: 'Riesgo de Mal Agudo de Montaña (AMS) — ascenso gradual obligatorio' },
  'sim.altitude.risk.hardTraining': { en: 'Intense training at this altitude is counterproductive — reduce load 40-50%', es: 'Entrenamiento intenso a esta altitud contraproducente — reducir carga 40-50%' },
  'sim.altitude.risk.spo2': { en: 'Estimated SpO2 __SPO2__% — continuous monitoring recommended', es: 'SpO2 estimada __SPO2__% — monitoreo continuo recomendado' },
  'sim.altitude.risk.shortExposure': { en: 'Short exposure — reduced performance without acclimatization benefits', es: 'Exposición corta — rendimiento reducido sin beneficios de aclimatación' },
  'sim.altitude.risk.lhtl': { en: 'Optimal conditions for LHTL protocol (Live High Train Low)', es: 'Condiciones óptimas para protocolo LHTL (vivir alto, entrenar bajo)' },

  'sim.altitude.rec.lhtl': { en: 'LHTL (live 2200-3000m, train 1200-1500m) — maximum erythropoietic stimulation with minimal loss of training quality', es: 'LHTL (vivir 2200-3000m, entrenar 1200-1500m) — máxima estimulación eritropoyética con mínima pérdida de calidad de entrenamiento' },
  'sim.altitude.rec.hydration': { en: 'Increase fluid intake 15-20% (increased ventilation = more respiratory water loss)', es: 'Aumentar ingesta hídrica 15-20% (mayor ventilación = más pérdida respiratoria de agua)' },
  'sim.altitude.rec.load': { en: 'Reduce intensity __PCT__% for the first 5 days. Reference pace rises ~__SECS__s/km', es: 'Reducir intensidad __PCT__% los primeros 5 días. El ritmo de referencia sube ~__SECS__s/km' },
  'sim.altitude.rec.iron': { en: 'Ensure ferritin >50 ng/mL before exposure (critical for erythropoiesis at altitude)', es: 'Asegurar ferritina >50 ng/ml antes de la exposición (crítico para eritropoyesis a altitud)' },
  'sim.altitude.rec.recovery': { en: 'Compensate for reduced sleep quality at altitude with active rest; HRV is a good adaptation marker', es: 'Compensar el sueño reducido en altitud con descanso activo; el HRV es un buen marcador de adaptación' },
  'sim.altitude.rec.medicalMonitoring': { en: 'Critical SpO2 — consider nocturnal pulse oximetry and descent if AMS symptoms persist >24h', es: 'SpO2 crítica — considerar oxímetro de pulso nocturno y descenso si síntomas de AMS persisten >24h' },
  'sim.altitude.rec.nutrition': { en: 'Increase caloric intake 10-15% (higher basal metabolic rate in hypoxia) and prioritize carbs over fats', es: 'Incrementar ingesta calórica 10-15% (mayor gasto metabólico basal en hipoxia) y priorizar CHO frente a grasas' },
  'sim.altitude.rec.optimalProtocol': { en: 'Optimal protocol', es: 'Protocolo óptimo' },
  'sim.altitude.rec.hydrationCat': { en: 'Hydration', es: 'Hidratación' },
  'sim.altitude.rec.trainingLoad': { en: 'Training load', es: 'Carga de entrenamiento' },
  'sim.altitude.rec.ironCat': { en: 'Iron', es: 'Hierro' },
  'sim.altitude.rec.recoveryCat': { en: 'Recovery', es: 'Recuperación' },
  'sim.altitude.rec.medicalCat': { en: 'Medical monitoring', es: 'Monitoreo médico' },
  'sim.altitude.rec.nutritionCat': { en: 'Nutrition', es: 'Nutrición' },

  'sim.inverse.title': { en: 'Inverse Simulation — Required VO2max for a Goal', es: 'Simulación Inversa — VO2max necesario para un objetivo' },
  'sim.inverse.targetTime': { en: 'Target time', es: 'Tiempo objetivo' },
  'sim.inverse.hours': { en: 'h', es: 'h' },
  'sim.inverse.minutes': { en: 'min', es: 'min' },
  'sim.inverse.seconds': { en: 'sec', es: 'seg' },
  'sim.inverse.calculate': { en: 'Calculate', es: 'Calcular' },
  'sim.inverse.requiredVO2max': { en: 'Required VO2max', es: 'VO2max necesario' },
  'sim.inverse.currentGap': { en: 'Gap', es: 'Diferencia' },
  'sim.inverse.achievable': { en: 'Goal achievable at current VO2max', es: 'Objetivo alcanzable con VO2max actual' },
  'sim.inverse.currentPace': { en: 'Pace at current VO2max', es: 'Ritmo con VO2max actual' },
  'sim.inverse.trainingProjection': { en: 'Training Progression Projection', es: 'Proyección de Progresión con Entrenamiento' },
  'sim.inverse.weeks': { en: 'weeks', es: 'semanas' },
  'sim.inverse.gap0': { en: 'You already have the required VO2max — focus on pacing and nutrition.', es: 'Ya tienes el VO2max necesario — enfócate en pacing y nutrición.' },
  'sim.inverse.gapSmall': { en: 'Small gap — achievable with 8-12 weeks of specific training.', es: 'Brecha pequeña — alcanzable con 8-12 semanas de entrenamiento específico.' },
  'sim.inverse.gapModerate': { en: 'Moderate gap — plan a 16-20 week block with high aerobic volume.', es: 'Brecha moderada — planifica un bloque de 16-20 semanas con alto volumen aeróbico.' },
  'sim.inverse.gapLarge': { en: 'Large gap — long-term goal (>6 months). Work progressively.', es: 'Brecha grande — objetivo a largo plazo (>6 meses). Trabaja progresivamente.' },

  'sim.zone.z1z2': { en: 'Z1-Z2 Aerobic', es: 'Z1-Z2 Aeróbico' },
  'sim.zone.z3': { en: 'Z3 Tempo', es: 'Z3 Tempo' },
  'sim.zone.z4plus': { en: 'Z4+ Threshold', es: 'Z4+ Umbral' },
  'sim.zone.z2': { en: 'Z2 Aerobic', es: 'Z2 Aeróbico' },
  'sim.zone.z4': { en: 'Z4 Threshold', es: 'Z4 Umbral' },
  'sim.zone.z5': { en: 'Z5 VO2max', es: 'Z5 VO2max' },
  'sim.zone.z3z4': { en: 'Z3-Z4 Threshold', es: 'Z3-Z4 Umbral' },
  'sim.zone.z6': { en: 'Z6 Neuromuscular', es: 'Z6 Neuromusc.' },
  'sim.zone.z7': { en: 'Z7 Anaerobic', es: 'Z7 Anaeróbico' },

  'sim.bonkWarning': { en: 'Estimated bonk at km __KM__ — pace degrades significantly after this point', es: 'Bonk estimado en km __KM__ — ritmo se degrada significativamente después de este punto' },
  'sim.glycogenDepletes': { en: 'Glycogen depletes at km __KM__ without race carb intake. Plan ~__RATE__g/h.', es: 'Glucógeno se agota en km __KM__ sin ingesta de CHO en carrera. Planificar ~__RATE__g/h.' },

  'sim.altBlock.title': { en: 'Altitude Block — Impact on Race Performance', es: 'Bloque de Altitud — Impacto en Rendimiento en Carrera' },
  'sim.altBlock.altBlock': { en: 'Altitude block', es: 'Bloque de altitud' },
  'sim.altBlock.altitude': { en: 'Altitude (m)', es: 'Altitud (m)' },
  'sim.altBlock.duration': { en: 'Duration (days)', es: 'Duración (días)' },
  'sim.altBlock.trainingLoad': { en: 'Training load', es: 'Carga de entrenamiento' },
  'sim.altBlock.light': { en: 'Light', es: 'Suave' },
  'sim.altBlock.moderate': { en: 'Moderate', es: 'Moderada' },
  'sim.altBlock.rest': { en: 'Rest', es: 'Descanso' },
  'sim.altBlock.restDesc': { en: 'No training', es: 'Sin entrenamiento' },
  'sim.altBlock.lightDesc': { en: '40-50% normal load', es: '40-50% carga normal' },
  'sim.altBlock.moderateDesc': { en: '60-70% normal load', es: '60-70% carga normal' },
  'sim.altBlock.hard': { en: 'Hard', es: 'Intenso' },
  'sim.altBlock.hardDesc': { en: '80-100% normal load', es: '80-100% carga normal' },
  'sim.altBlock.simulate': { en: 'Simulate altitude block', es: 'Simular bloque de altitud' },
  'sim.altBlock.raceConfig': { en: 'Race configuration', es: 'Configuración de carrera' },
  'sim.altBlock.run': { en: 'Run comparison', es: 'Ejecutar comparativa' },
  'sim.altBlock.seaLevel': { en: 'Sea level', es: 'Nivel del mar' },
  'sim.altBlock.postAlt': { en: 'Post-altitude', es: 'Post-altitud' },
  'sim.altBlock.diff': { en: 'Difference', es: 'Diferencia' },
  'sim.altBlock.vo2maxGain': { en: 'VO2max gain', es: 'Ganancia VO2max' },
  'sim.altBlock.perfImprovement': { en: 'Performance improvement', es: 'Mejora de rendimiento' },
  'sim.altBlock.timeImprovement': { en: 'Time improvement', es: 'Mejora de tiempo' },
  'sim.altBlock.projectedTime': { en: 'Projected time', es: 'Tiempo proyectado' },
  'sim.altBlock.bestWindow': { en: 'Best competition window', es: 'Ventana óptima de competición' },
  'sim.altBlock.bestWindowText': { en: '7-21 days post-descent for peak haematological adaptation', es: '7-21 días post-descenso para pico de adaptación hematológica' },

  'vo2ref.title': { en: 'VO₂max / Lactate Comparison', es: 'Comparativa VO₂max / Lactato' },
  'vo2ref.subtitle': { en: 'Comparison with published sports populations', es: 'Comparación con poblaciones deportivas publicadas' },
  'vo2ref.sportDiscipline': { en: 'Sport / Discipline', es: 'Deporte / Disciplina' },
  'vo2ref.athleteVO2': { en: 'Athlete VO₂max', es: 'VO₂max del atleta' },
  'vo2ref.populationType': { en: 'Population Type', es: 'Tipo de Población' },
  'vo2ref.all': { en: 'All', es: 'Todos' },
  'vo2ref.lactateThresholds': { en: 'Lactate Thresholds', es: 'Umbrales de Lactato' },
  'vo2ref.closestLevel': { en: 'Closest reference level', es: 'Nivel de referencia más cercano' },
  'vo2ref.vsMean': { en: 'vs. mean', es: 'vs. media' },
  'vo2ref.competitiveSpectrum': { en: 'Competitive spectrum', es: 'Espectro competitivo' },
  'vo2ref.valuesPerLevel': { en: 'Values per level', es: 'Valores por nivel' },
  'vo2ref.athlete': { en: 'Athlete', es: 'Atleta' },
  'vo2ref.yourRange': { en: 'Your range', es: 'Tu rango' },
  'vo2ref.custom': { en: 'Custom', es: 'Personalizado' },
  'vo2ref.lt1Athlete': { en: 'Athlete LT1', es: 'LT1 del atleta' },
  'vo2ref.lt2Athlete': { en: 'Athlete LT2', es: 'LT2 del atleta' },
  'vo2ref.lactateRefs': { en: 'Lactate Threshold References', es: 'Referencias de Umbral de Lactato' },
  'vo2ref.noLactateData': { en: 'No lactate data available for this selection.', es: 'No hay datos de lactato disponibles para esta selección.' },
  'vo2ref.lt1Aerobic': { en: 'LT1 (Aerobic Threshold)', es: 'LT1 (Umbral Aeróbico)' },
  'vo2ref.lt2Anaerobic': { en: 'LT2 (Anaerobic Threshold)', es: 'LT2 (Umbral Anaeróbico)' },
  'vo2ref.athleteLabel': { en: 'Athlete', es: 'Atleta' },
  'vo2ref.hideRefs': { en: 'Hide scientific references', es: 'Ocultar referencias científicas' },
  'vo2ref.showRefs': { en: 'View scientific references', es: 'Ver referencias científicas' },
  'vo2ref.noData': { en: 'No reference data available for', es: 'No hay datos de referencia disponibles para' },

  'reportBuilder.professionalNotes': { en: 'Professional Notes', es: 'Notas Profesionales' },
  'reportBuilder.professionalNotesDesc': { en: 'Add conclusions or recommendations to include in this report', es: 'Agregá conclusiones o recomendaciones para incluir en este informe' },
  'reportBuilder.professionalNotesPlaceholder': { en: 'Write your professional conclusions, training recommendations, and observations here. These will appear in the Conclusions section of the PDF.', es: 'Escribí tus conclusiones profesionales, recomendaciones de entrenamiento y observaciones aquí. Aparecerán en la sección Conclusiones del PDF.' },

  // Biochemical Lab
  'bio.title': { en: 'Biochemical Lab', es: 'Lab Bioquímico' },
  'bio.subtitle': { en: 'Blood marker analysis and interpretation', es: 'Análisis e interpretación de marcadores sanguíneos' },
  'bio.tab.input': { en: 'New Test', es: 'Nuevo Test' },
  'bio.tab.results': { en: 'Results', es: 'Resultados' },
  'bio.tab.trends': { en: 'Trends', es: 'Tendencias' },
  'bio.changeAthlete': { en: 'Change Athlete', es: 'Cambiar Atleta' },
  'bio.testDate': { en: 'Test Date', es: 'Fecha del Test' },
  'bio.notes': { en: 'Notes', es: 'Notas' },
  'bio.notesPlaceholder': { en: 'Fasting state, time of day, etc.', es: 'Estado de ayuno, hora del día, etc.' },
  'bio.optimal': { en: 'Optimal', es: 'Óptimo' },
  'bio.markersEntered': { en: 'markers entered', es: 'marcadores ingresados' },
  'bio.saving': { en: 'Saving...', es: 'Guardando...' },
  'bio.saveTest': { en: 'Save Test', es: 'Guardar Test' },
  'bio.errorNoMarkers': { en: 'Enter at least one marker value', es: 'Ingresá al menos un valor de marcador' },
  'bio.noResults': { en: 'No biochemical tests recorded yet', es: 'No hay tests bioquímicos registrados aún' },
  'bio.globalScore': { en: 'Global Biochemical Score', es: 'Score Bioquímico Global' },
  'bio.healthFlags': { en: 'Health Flags', es: 'Alertas de Salud' },
  'bio.noTrends': { en: 'Not enough data for trend analysis', es: 'No hay datos suficientes para análisis de tendencias' },
  'bio.needMultipleTests': { en: 'Record at least 2 tests to see trends', es: 'Registrá al menos 2 tests para ver tendencias' },
  'bio.globalTrend': { en: 'Global Score Trend', es: 'Tendencia del Score Global' },

  // Biochemical domains
  'bio.domain.oxygenTransport': { en: 'Oxygen Transport', es: 'Transporte de Oxígeno' },
  'bio.domain.recovery': { en: 'Recovery', es: 'Recuperación' },
  'bio.domain.inflammation': { en: 'Inflammation', es: 'Inflamación' },
  'bio.domain.hormonal': { en: 'Hormonal', es: 'Hormonal' },
  'bio.domain.energyAvailability': { en: 'Energy Availability', es: 'Disponibilidad Energética' },
  'bio.domain.nutrition': { en: 'Nutrition', es: 'Nutrición' },
  'bio.domain.metabolicHealth': { en: 'Metabolic Health', es: 'Salud Metabólica' },
  'bio.domain.hydrationRenal': { en: 'Hydration & Renal', es: 'Hidratación y Renal' },

  // Biochemical markers
  'bio.marker.hemoglobin': { en: 'Hemoglobin', es: 'Hemoglobina' },
  'bio.marker.hematocrit': { en: 'Hematocrit', es: 'Hematocrito' },
  'bio.marker.ferritin': { en: 'Ferritin', es: 'Ferritina' },
  'bio.marker.iron': { en: 'Iron', es: 'Hierro' },
  'bio.marker.transferrinSat': { en: 'Transferrin Sat.', es: 'Sat. Transferrina' },
  'bio.marker.ck': { en: 'CK', es: 'CK' },
  'bio.marker.ldh': { en: 'LDH', es: 'LDH' },
  'bio.marker.urea': { en: 'Urea', es: 'Urea' },
  'bio.marker.cortisol': { en: 'Cortisol', es: 'Cortisol' },
  'bio.marker.crp': { en: 'CRP', es: 'PCR' },
  'bio.marker.esr': { en: 'ESR', es: 'VSG' },
  'bio.marker.wbc': { en: 'WBC', es: 'Leucocitos' },
  'bio.marker.nlr': { en: 'N/L Ratio', es: 'Ratio N/L' },
  'bio.marker.testosterone': { en: 'Testosterone', es: 'Testosterona' },
  'bio.marker.cortisolAm': { en: 'Cortisol (AM)', es: 'Cortisol (AM)' },
  'bio.marker.tsh': { en: 'TSH', es: 'TSH' },
  'bio.marker.freeT4': { en: 'Free T4', es: 'T4 Libre' },
  'bio.marker.igf1': { en: 'IGF-1', es: 'IGF-1' },
  'bio.marker.glucoseFasting': { en: 'Fasting Glucose', es: 'Glucosa en Ayunas' },
  'bio.marker.insulinFasting': { en: 'Fasting Insulin', es: 'Insulina en Ayunas' },
  'bio.marker.triglycerides': { en: 'Triglycerides', es: 'Triglicéridos' },
  'bio.marker.freeFA': { en: 'Free Fatty Acids', es: 'Ácidos Grasos Libres' },
  'bio.marker.vitaminD': { en: 'Vitamin D', es: 'Vitamina D' },
  'bio.marker.vitaminB12': { en: 'Vitamin B12', es: 'Vitamina B12' },
  'bio.marker.folate': { en: 'Folate', es: 'Folato' },
  'bio.marker.magnesium': { en: 'Magnesium', es: 'Magnesio' },
  'bio.marker.zinc': { en: 'Zinc', es: 'Zinc' },
  'bio.marker.hba1c': { en: 'HbA1c', es: 'HbA1c' },
  'bio.marker.hdl': { en: 'HDL', es: 'HDL' },
  'bio.marker.ldl': { en: 'LDL', es: 'LDL' },
  'bio.marker.totalCholesterol': { en: 'Total Cholesterol', es: 'Colesterol Total' },
  'bio.marker.creatinine': { en: 'Creatinine', es: 'Creatinina' },
  'bio.marker.bun': { en: 'BUN', es: 'BUN' },
  'bio.marker.sodium': { en: 'Sodium', es: 'Sodio' },
  'bio.marker.potassium': { en: 'Potassium', es: 'Potasio' },

  // Neuromuscular Lab tabs
  'neuro.title': { en: 'Neuromuscular Lab', es: 'Lab Neuromuscular' },
  'neuro.subtitle': { en: 'Neuromuscular assessment and performance profiling', es: 'Evaluación neuromuscular y perfilado de rendimiento' },
  'neuro.tab.forceVelocity': { en: 'Force Velocity Profile', es: 'Perfil Fuerza-Velocidad' },
  'neuro.tab.jumpTesting': { en: 'Jump Testing', es: 'Tests de Salto' },
  'neuro.tab.sprintTesting': { en: 'Sprint Testing', es: 'Tests de Sprint' },
  'neuro.tab.strengthTesting': { en: 'Strength Testing', es: 'Tests de Fuerza' },
  'neuro.tab.vbt': { en: 'Velocity Based Training', es: 'Entrenamiento Basado en Velocidad' },
  'neuro.tab.fatigueMonitoring': { en: 'Fatigue Monitoring', es: 'Monitoreo de Fatiga' },

  // Health Flags
  'healthFlags.title': { en: 'Health Flags', es: 'Alertas de Salud' },
  'healthFlags.subtitle': { en: 'Cross-laboratory health alerts and monitoring', es: 'Alertas de salud y monitoreo inter-laboratorio' },
  'healthFlags.normal': { en: 'Normal', es: 'Normal' },
  'healthFlags.monitor': { en: 'Monitor', es: 'Monitorear' },
  'healthFlags.attention': { en: 'Attention', es: 'Atención' },
  'healthFlags.noFlags': { en: 'No Active Flags', es: 'Sin Alertas Activas' },
  'healthFlags.noFlagsDesc': { en: 'Health flags will appear here when generated from laboratory assessments.', es: 'Las alertas de salud aparecerán aquí cuando se generen a partir de evaluaciones de laboratorio.' },
  'healthFlags.fromBiochemical': { en: 'From biochemical analysis', es: 'Del análisis bioquímico' },
  'healthFlags.selectAthlete': { en: 'Select an athlete to view their health flags', es: 'Seleccioná un atleta para ver sus alertas de salud' },
  'healthFlags.fromEngine': { en: 'Physiological integration flags', es: 'Alertas de integración fisiológica' },

  // Physiology Engine
  'engine.readinessScore': { en: 'Athlete Readiness', es: 'Disposición del Atleta' },
  'engine.limitingFactor': { en: 'Limiting Factor', es: 'Factor Limitante' },
  'engine.noData': { en: 'No data available', es: 'Sin datos disponibles' },
  'engine.noDataAvailable': { en: 'Insufficient data to compute readiness. Complete lab assessments to generate your physiological profile.', es: 'Datos insuficientes para calcular la disposición. Completá evaluaciones de laboratorio para generar tu perfil fisiológico.' },
  'engine.flags': { en: 'Physiological Flags', es: 'Alertas Fisiológicas' },

  'engine.domain.aerobic': { en: 'Aerobic System', es: 'Sistema Aeróbico' },
  'engine.domain.neuromuscular': { en: 'Neuromuscular System', es: 'Sistema Neuromuscular' },
  'engine.domain.biological': { en: 'Biological Health', es: 'Salud Biológica' },
  'engine.domain.hydration': { en: 'Hydration & Env. Stress', es: 'Hidratación y Estrés Ambiental' },

  'engine.interp.aerobic.good': { en: 'Strong aerobic capacity with efficient lactate clearance.', es: 'Capacidad aeróbica sólida con eficiente aclaramiento de lactato.' },
  'engine.interp.aerobic.moderate': { en: 'Moderate aerobic development. LT stability could improve.', es: 'Desarrollo aeróbico moderado. La estabilidad del umbral puede mejorar.' },
  'engine.interp.aerobic.low': { en: 'Reduced aerobic efficiency. Priority development area.', es: 'Eficiencia aeróbica reducida. Área de desarrollo prioritaria.' },
  'engine.interp.neuro.good': { en: 'Excellent neuromuscular function and power output.', es: 'Excelente función neuromuscular y producción de potencia.' },
  'engine.interp.neuro.moderate': { en: 'Adequate neuromuscular capacity with room for improvement.', es: 'Capacidad neuromuscular adecuada con margen de mejora.' },
  'engine.interp.neuro.low': { en: 'Neuromuscular fatigue or detraining detected.', es: 'Fatiga neuromuscular o desentrenamiento detectado.' },
  'engine.interp.bio.good': { en: 'Healthy biological markers supporting performance.', es: 'Marcadores biológicos saludables que apoyan el rendimiento.' },
  'engine.interp.bio.moderate': { en: 'Some markers require monitoring. No critical issues.', es: 'Algunos marcadores requieren monitoreo. Sin problemas críticos.' },
  'engine.interp.bio.low': { en: 'Significant biological stress detected. Review markers.', es: 'Estrés biológico significativo detectado. Revisar marcadores.' },
  'engine.interp.hydration.good': { en: 'Well hydrated with appropriate thermoregulatory response.', es: 'Bien hidratado con respuesta termorreguladora apropiada.' },
  'engine.interp.hydration.moderate': { en: 'Mild hydration or heat stress indicators present.', es: 'Indicadores leves de estrés hídrico o calórico presentes.' },
  'engine.interp.hydration.low': { en: 'Significant hydration deficit or heat stress detected.', es: 'Déficit hídrico significativo o estrés por calor detectado.' },

  'engine.limit.none': { en: 'No limiting factors identified', es: 'Sin factores limitantes identificados' },
  'engine.limit.aerobicLimitation': { en: 'Aerobic capacity decline', es: 'Descenso de capacidad aeróbica' },
  'engine.limit.neuromuscularFatigue': { en: 'Neuromuscular fatigue accumulation', es: 'Acumulación de fatiga neuromuscular' },
  'engine.limit.ironTransport': { en: 'Iron/oxygen transport limitation', es: 'Limitación de transporte de hierro/oxígeno' },
  'engine.limit.hormonalStress': { en: 'Hormonal stress response', es: 'Respuesta de estrés hormonal' },
  'engine.limit.hydrationHeat': { en: 'Hydration/heat stress', es: 'Estrés hídrico/calórico' },

  'engine.flag.aerobicDecline': { en: 'Aerobic capacity decline detected', es: 'Descenso de capacidad aeróbica detectado' },
  'engine.flag.neuromuscularFatigue': { en: 'Neuromuscular fatigue accumulation', es: 'Acumulación de fatiga neuromuscular' },
  'engine.flag.biologicalStress': { en: 'Biological stress markers elevated', es: 'Marcadores de estrés biológico elevados' },
  'engine.flag.hydrationImbalance': { en: 'Hydration imbalance under stress', es: 'Desequilibrio hídrico bajo estrés' },
  'engine.flag.systemicFatigue': { en: 'General systemic fatigue state', es: 'Estado de fatiga sistémica general' },
};

let _currentLanguage: Language = 'en';

export function getCurrentLanguage(): Language {
  return _currentLanguage;
}

export function tGlobal(key: string): string {
  return translations[key]?.[_currentLanguage] || key;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'es') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    _currentLanguage = language;
  }, [language]);

  useEffect(() => {
    _currentLanguage = language;
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
